#!/usr/bin/env python3
import os
file_location = os.path.dirname(__file__)
executable_binary_name = 'main.cpython-38.pyc'
os.system('cd {} && python3 ./{}'.format(file_location, executable_binary_name))
